name: Project linting and testing

env:
  mongodb_username: ${{ secrets.MONGODB_USERNAME }}
  mongodb_password: ${{ secrets.MONGODB_PASSWORD }}
  mongodb_connection: ${{ secrets.MONGODB_CONNECTION }}
  mongodb_raw_cluster: ${{ secrets.MONGODB_RAW_CLUSTER }}

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with pytest
        run: |
          python -m pytest
